version: "3.8"

services:
  traefik:
    image: traefik:3.0
    restart: always
    networks:
      - traefik-public
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/etc/traefik/acme.json
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    restart: always
    networks:
      - traefik-public
      - default
    env_file:
      - .env
    environment:
      - DATABASE_API_URL=${DATABASE_API_URL?Variable not set}
      - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - SENTRY_DSN=${SENTRY_DSN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: ./backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.api-http.rule=Host(`api.roamingproxy.com`)
      - traefik.http.routers.api-http.entrypoints=http
      - traefik.http.services.api-service.loadbalancer.server.port=8000

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}"
    restart: always
    networks:
      - traefik-public
      - default
    env_file:
      - .env
    build:
      context: ./frontend
    environment:
      - NGINX_PROXY_BUFFER_SIZE=128k
      - NGINX_PROXY_BUFFERS=4 256k
      - NGINX_LARGE_CLIENT_HEADER_BUFFERS=4 16k
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.dashboard.rule=Host(`cloud.roamingproxy.com`)
      - traefik.http.routers.dashboard.entrypoints=http
      - traefik.http.services.dashboard.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true