version: "3.8"

services:
  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-public
      - default
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
      - ADMINER_DEFAULT_SERVER=${POSTGRES_SERVER?Variable not set}
      - ADMINER_DEFAULT_DB=${POSTGRES_DB?Variable not set}
      - ADMINER_DEFAULT_USERNAME=${POSTGRES_USER?Variable not set}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer.rule=Host(`adminer.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer.entrypoints=http
      - traefik.http.services.${STACK_NAME?Variable not set}-adminer.loadbalancer.server.port=8080

  backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    restart: always
    networks:
      - traefik-public
      - default
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - POSTGRES_SERVER=${POSTGRES_SERVER?Variable not set}
      - POSTGRES_PORT=${POSTGRES_PORT?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - SENTRY_DSN=${SENTRY_DSN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.api-http.rule=Host(`api.roamingproxy.com`)
      - traefik.http.routers.api-http.entrypoints=http
      - traefik.http.services.api-service.loadbalancer.server.port=8000

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}"
    restart: always
    networks:
      - traefik-public
      - default
    env_file:
      - .env
    build:
      context: ./frontend
    environment:
      - NGINX_PROXY_BUFFER_SIZE=128k
      - NGINX_PROXY_BUFFERS=4 256k
      - NGINX_LARGE_CLIENT_HEADER_BUFFERS=4 16k
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.dashboard.rule=Host(`cloud.roamingproxy.com`)
      - traefik.http.routers.dashboard.entrypoints=http
      - traefik.http.services.dashboard.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true